apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-pyrx
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xeoa-tenant/quarkus/devfile-sample-code-with-quarkus-pyrx@sha256:b543450746c88eb3a19d6931cb3fcd9337112f5ea29143f2dc4078034f5834fb
        name: my-java-quarkus
        resources: {}
status: {}
