apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-pyrx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-pyrx
    app.kubernetes.io/part-of: quarkus
  name: devfile-sample-code-with-quarkus-pyrx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-pyrx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-pyrx
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xeoa-tenant/quarkus/devfile-sample-code-with-quarkus-pyrx@sha256:b543450746c88eb3a19d6931cb3fcd9337112f5ea29143f2dc4078034f5834fb
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
